app:
  client:
    port: 8080
  payment:
    port: 8081
  subscriber:
    port: 8082

postgres:
  host: postgres
  port: 5432
  user: postgres
  password: postgres
  dbname: orderdb
  sslmode: disable
  timezone: America/Sao_Paulo
  
mongo:
  host: mongo
  port: 27017
  user: user
  password: password
  collection_name: subscriptions
  database_name: paymentdb




