version: '3.8'

services:
  subscriber:
    build:
      context: .
      dockerfile: cmd/subscriber/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - MONGO_URI=mongodb://user:password@localhost:27017

  payment:
    build:
      context: .
      dockerfile: cmd/payment/Dockerfile
    ports:
      - "8081:8080"
    depends_on:
      - db
    environment:
      - MONGO_URI=mongodb://user:password@localhost:27017

  db:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongodb_data:/data/db
volumes:
  mongodb_data: